/*
 * This file is generated by jOOQ.
 */
package com.gatesma.springjooq.jooq.tables.daos;


import com.gatesma.springjooq.jooq.tables.BookToBookStore;
import com.gatesma.springjooq.jooq.tables.records.BookToBookStoreRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookToBookStoreDao extends DAOImpl<BookToBookStoreRecord, com.gatesma.springjooq.jooq.tables.pojos.BookToBookStore, Record2<String, Integer>> {

    /**
     * Create a new BookToBookStoreDao without any configuration
     */
    public BookToBookStoreDao() {
        super(BookToBookStore.BOOK_TO_BOOK_STORE, com.gatesma.springjooq.jooq.tables.pojos.BookToBookStore.class);
    }

    /**
     * Create a new BookToBookStoreDao with an attached configuration
     */
    public BookToBookStoreDao(Configuration configuration) {
        super(BookToBookStore.BOOK_TO_BOOK_STORE, com.gatesma.springjooq.jooq.tables.pojos.BookToBookStore.class, configuration);
    }

    @Override
    public Record2<String, Integer> getId(com.gatesma.springjooq.jooq.tables.pojos.BookToBookStore object) {
        return compositeKeyRecord(object.getName(), object.getBookId());
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gatesma.springjooq.jooq.tables.pojos.BookToBookStore> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(BookToBookStore.BOOK_TO_BOOK_STORE.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.gatesma.springjooq.jooq.tables.pojos.BookToBookStore> fetchByName(String... values) {
        return fetch(BookToBookStore.BOOK_TO_BOOK_STORE.NAME, values);
    }

    /**
     * Fetch records that have <code>book_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gatesma.springjooq.jooq.tables.pojos.BookToBookStore> fetchRangeOfBookId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(BookToBookStore.BOOK_TO_BOOK_STORE.BOOK_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>book_id IN (values)</code>
     */
    public List<com.gatesma.springjooq.jooq.tables.pojos.BookToBookStore> fetchByBookId(Integer... values) {
        return fetch(BookToBookStore.BOOK_TO_BOOK_STORE.BOOK_ID, values);
    }

    /**
     * Fetch records that have <code>stock BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.gatesma.springjooq.jooq.tables.pojos.BookToBookStore> fetchRangeOfStock(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(BookToBookStore.BOOK_TO_BOOK_STORE.STOCK, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>stock IN (values)</code>
     */
    public List<com.gatesma.springjooq.jooq.tables.pojos.BookToBookStore> fetchByStock(Integer... values) {
        return fetch(BookToBookStore.BOOK_TO_BOOK_STORE.STOCK, values);
    }
}
