/*
 * This file is generated by jOOQ.
 */
package com.gatesma.springjooq.jooq;


import com.gatesma.springjooq.jooq.tables.Author;
import com.gatesma.springjooq.jooq.tables.Book;
import com.gatesma.springjooq.jooq.tables.BookStore;
import com.gatesma.springjooq.jooq.tables.BookToBookStore;
import com.gatesma.springjooq.jooq.tables.Language;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqDemo extends SchemaImpl {

    private static final long serialVersionUID = 280291192;

    /**
     * The reference instance of <code>jooq_demo</code>
     */
    public static final JooqDemo JOOQ_DEMO = new JooqDemo();

    /**
     * The table <code>jooq_demo.author</code>.
     */
    public final Author AUTHOR = com.gatesma.springjooq.jooq.tables.Author.AUTHOR;

    /**
     * The table <code>jooq_demo.book</code>.
     */
    public final Book BOOK = com.gatesma.springjooq.jooq.tables.Book.BOOK;

    /**
     * The table <code>jooq_demo.book_store</code>.
     */
    public final BookStore BOOK_STORE = com.gatesma.springjooq.jooq.tables.BookStore.BOOK_STORE;

    /**
     * The table <code>jooq_demo.book_to_book_store</code>.
     */
    public final BookToBookStore BOOK_TO_BOOK_STORE = com.gatesma.springjooq.jooq.tables.BookToBookStore.BOOK_TO_BOOK_STORE;

    /**
     * The table <code>jooq_demo.language</code>.
     */
    public final Language LANGUAGE = com.gatesma.springjooq.jooq.tables.Language.LANGUAGE;

    /**
     * No further instances allowed
     */
    private JooqDemo() {
        super("jooq_demo", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Author.AUTHOR,
            Book.BOOK,
            BookStore.BOOK_STORE,
            BookToBookStore.BOOK_TO_BOOK_STORE,
            Language.LANGUAGE);
    }
}
