/*
 * This file is generated by jOOQ.
 */
package com.gatesma.springjooq.jooq;


import com.gatesma.springjooq.jooq.tables.Author;
import com.gatesma.springjooq.jooq.tables.Book;
import com.gatesma.springjooq.jooq.tables.BookStore;
import com.gatesma.springjooq.jooq.tables.BookToBookStore;
import com.gatesma.springjooq.jooq.tables.Language;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in jooq_demo
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jooq_demo.author</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>jooq_demo.book</code>.
     */
    public static final Book BOOK = Book.BOOK;

    /**
     * The table <code>jooq_demo.book_store</code>.
     */
    public static final BookStore BOOK_STORE = BookStore.BOOK_STORE;

    /**
     * The table <code>jooq_demo.book_to_book_store</code>.
     */
    public static final BookToBookStore BOOK_TO_BOOK_STORE = BookToBookStore.BOOK_TO_BOOK_STORE;

    /**
     * The table <code>jooq_demo.language</code>.
     */
    public static final Language LANGUAGE = Language.LANGUAGE;
}
